"""Independent re-execution that never trusts a bundled certificate's results."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

from modelpact.contracts.ast import BehaviorContract
from modelpact.contracts.holdout import HoldoutPhase, SealedHoldoutGate
from modelpact.util.hashing import sha256_file
from modelpact.util.paths import resolve_inside, safe_relative_path
from modelpact.verify.certificate import (
    VerificationCertificate,
    build_certificate,
    validate_certificate,
)
from modelpact.verify.engine import (
    AssertionRecordProvider,
    ExecutionIdentity,
    VerificationReport,
    verify_contract,
)
from modelpact.verify.generation import FreeGenerationRecord


@dataclass(frozen=True, slots=True)
class IndependentVerificationResult:
    report: VerificationReport
    certificate: VerificationCertificate
    prior_certificate_differences: tuple[str, ...]


def hash_artifacts(
    root: str | Path,
    paths: Sequence[str],
    *,
    max_file_bytes: int = 64 * 1024 * 1024 * 1024,
) -> dict[str, str]:
    """Hash an explicit, traversal-safe artifact set in deterministic order."""

    if len(paths) != len(set(paths)):
        raise ValueError("artifact paths must be unique")
    result: dict[str, str] = {}
    for relative in sorted(paths):
        safe_relative_path(relative)
        path = resolve_inside(root, relative)
        if not path.is_file():
            raise FileNotFoundError(path)
        result[relative] = sha256_file(path, max_bytes=max_file_bytes)
    return result


def _prior_differences(
    prior: VerificationCertificate | None,
    current: VerificationCertificate,
) -> tuple[str, ...]:
    if prior is None:
        return ()
    differences: list[str] = []
    comparisons = (
        ("patch_id", prior.patch_id, current.patch_id),
        ("base_signature", prior.base_signature, current.base_signature),
        ("tokenizer_hash", prior.tokenizer_hash, current.tokenizer_hash),
        ("contract_hashes", prior.contract_hashes, current.contract_hashes),
        ("probe_hashes", prior.probe_hashes, current.probe_hashes),
        ("verification_outcome", prior.verification_outcome, current.verification_outcome),
        ("claims", prior.claims, current.claims),
        # Independent execution does not re-derive a rebase, so a bundled
        # rebase_result is always reported as differing rather than silently
        # treated as confirmed by a run that never checked it.
        ("rebase_result", prior.rebase_result, current.rebase_result),
    )
    for name, old, new in comparisons:
        if old != new:
            differences.append(name)
    return tuple(differences)


def independently_verify(
    contract: BehaviorContract,
    *,
    patch_id: str,
    identity: ExecutionIdentity,
    provider: AssertionRecordProvider,
    checkpoint_hashes: Mapping[str, str],
    artifact_root: str | Path,
    artifact_paths: Sequence[str],
    probe_hashes: Mapping[str, str],
    schemas: Mapping[str, Mapping[str, object]] | None = None,
    free_generation_records: Sequence[FreeGenerationRecord] = (),
    include_holdout: bool = True,
    prior_certificate: VerificationCertificate | None = None,
) -> IndependentVerificationResult:
    """Re-hash, re-apply through the caller's backend, and re-run contracts.

    ``prior_certificate`` is comparison-only.  None of its outcomes or artifact
    hashes are used to build the new certificate.
    """

    artifacts = hash_artifacts(artifact_root, artifact_paths)
    gate: SealedHoldoutGate | None = None
    capability = None
    execute_holdout = include_holdout and contract.holdout.configured
    if execute_holdout:
        gate = SealedHoldoutGate(contract, allow_independent=True)
        capability = gate.authorize(
            phase=HoldoutPhase.INDEPENDENT_VERIFICATION,
            candidate_id=patch_id,
        )
    report = verify_contract(
        contract,
        identity=identity,
        provider=provider,
        schemas=schemas,
        free_generation_records=free_generation_records,
        probe_hashes=probe_hashes,
        include_holdout=execute_holdout,
        holdout_gate=gate,
        holdout_capability=capability,
    )
    certificate = build_certificate(
        report,
        contract,
        patch_id=patch_id,
        checkpoint_hashes=checkpoint_hashes,
        artifact_hashes=artifacts,
        additional_warnings=(
            "Certificate was regenerated by independent execution; "
            "bundled results were not trusted.",
        ),
    )
    validate_certificate(certificate, artifact_root=artifact_root)
    return IndependentVerificationResult(
        report=report,
        certificate=certificate,
        prior_certificate_differences=_prior_differences(prior_certificate, certificate),
    )


__all__ = ["IndependentVerificationResult", "hash_artifacts", "independently_verify"]
