"""Machine-readable status and claim taxonomies.

These enums are deliberately strings: artifacts must remain readable without
importing ModelPact and unknown future values must never be interpreted as a
successful legacy value.
"""

from __future__ import annotations

from enum import StrEnum


class VerificationOutcome(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNSUPPORTED = "UNSUPPORTED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class PatchClaim(StrEnum):
    BASE_COMPATIBLE = "BASE_COMPATIBLE"
    TARGET_OBJECTIVE_OPTIMIZED = "TARGET_OBJECTIVE_OPTIMIZED"
    TARGET_ASSERTIONS_VERIFIED = "TARGET_ASSERTIONS_VERIFIED"
    PRESERVATION_ASSERTIONS_VERIFIED = "PRESERVATION_ASSERTIONS_VERIFIED"
    SEALED_HOLDOUT_VERIFIED = "SEALED_HOLDOUT_VERIFIED"
    FREE_GENERATION_VERIFIED = "FREE_GENERATION_VERIFIED"
    PATCH_MINIMIZED_WITHIN_BUDGET = "PATCH_MINIMIZED_WITHIN_BUDGET"


class CompositionClaim(StrEnum):
    COMPOSITION_CLOSED = "COMPOSITION_CLOSED"
    COMPOSITION_DEGRADED = "COMPOSITION_DEGRADED"
    SEMANTIC_CONFLICT = "SEMANTIC_CONFLICT"
    STRUCTURAL_INCOMPATIBILITY = "STRUCTURAL_INCOMPATIBILITY"
    STATIC_CONTRACT_CONTRADICTION = "STATIC_CONTRACT_CONTRADICTION"
    EMPIRICALLY_INFEASIBLE_WITHIN_BUDGET = "EMPIRICALLY_INFEASIBLE_WITHIN_BUDGET"


class RebaseClaim(StrEnum):
    DIRECT_TRANSPLANT_VERIFIED = "DIRECT_TRANSPLANT_VERIFIED"
    SEMANTIC_REBASE_VERIFIED = "SEMANTIC_REBASE_VERIFIED"
    REBASE_FAILED = "REBASE_FAILED"
    REBASE_INCONCLUSIVE = "REBASE_INCONCLUSIVE"


class AuditClaim(StrEnum):
    EXHAUSTIVE_COMPOSITION_AUDIT = "EXHAUSTIVE_COMPOSITION_AUDIT"
    BUDGETED_COMPOSITION_AUDIT = "BUDGETED_COMPOSITION_AUDIT"
    FAILING_SUBSET_FOUND = "FAILING_SUBSET_FOUND"
    NO_FAILURE_FOUND_WITHIN_BUDGET = "NO_FAILURE_FOUND_WITHIN_BUDGET"


class MinimalityClaim(StrEnum):
    GLOBAL_MINIMUM = "GLOBAL_MINIMUM"
    MODULE_ONE_MINIMAL = "MODULE_ONE_MINIMAL"
    RANK_LOCAL_MINIMUM = "RANK_LOCAL_MINIMUM"
    BUDGET_MINIMAL = "BUDGET_MINIMAL"
    UNMINIMIZED = "UNMINIMIZED"


class ContractCoverage(StrEnum):
    FINITE_EXHAUSTIVE = "FINITE_EXHAUSTIVE"
    FINITE_PARTIAL = "FINITE_PARTIAL"
    SAMPLED_STATISTICAL = "SAMPLED_STATISTICAL"
    SEARCH_AUDITED = "SEARCH_AUDITED"
    SEALED_HOLDOUT = "SEALED_HOLDOUT"


class CompositionCoverage(StrEnum):
    EXHAUSTIVE_SUBSETS = "EXHAUSTIVE_SUBSETS"
    PAIRWISE_ONLY = "PAIRWISE_ONLY"
    ACTIVE_BUDGETED = "ACTIVE_BUDGETED"
    INDIVIDUAL_ONLY = "INDIVIDUAL_ONLY"


class ReproducibilityGrade(StrEnum):
    BITWISE_RUNTIME_MOUNT = "BITWISE_RUNTIME_MOUNT"
    DETERMINISTIC_WITHIN_ENVIRONMENT = "DETERMINISTIC_WITHIN_ENVIRONMENT"
    NUMERICALLY_REPRODUCIBLE = "NUMERICALLY_REPRODUCIBLE"
    STATISTICALLY_REPRODUCIBLE = "STATISTICALLY_REPRODUCIBLE"
    UNAUDITED = "UNAUDITED"


class ReversionGrade(StrEnum):
    RUNTIME_UNMOUNT_EXACT = "RUNTIME_UNMOUNT_EXACT"
    BASE_HASH_RESTORED = "BASE_HASH_RESTORED"
    NUMERIC_DELTA_INVERSE = "NUMERIC_DELTA_INVERSE"
    SEMANTIC_STACK_RECOMPILED = "SEMANTIC_STACK_RECOMPILED"
    REVERT_FAILED = "REVERT_FAILED"


SUCCESS_OUTCOMES: frozenset[VerificationOutcome] = frozenset({VerificationOutcome.PASS})

